import Head from 'next/head';
import { Banner, Clients, Solutions, Technologies } from '../components';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Thoughtwin</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Banner />
      <Solutions />
      <Technologies />
      <Clients />
    </div>
  );
}
